image: ubuntu:latest

definitions:
  services:
    redis:
      image: redis:alpine
      environment:
        REDIS_PASSWORD: 'secret'
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: 'pipelines'
        MYSQL_ROOT_PASSWORD: 'let_me_in'
  steps:
    - name: setup
      image: ubuntu:latest
      packages:
        - curl
        - wget
        - dnsutils
        - iputils-ping
      script: |
        echo "Setting up environment..."
        echo "Setup completed"

    - name: test-dns
      image: ubuntu:latest
      packages:
        - iputils-ping
        - dnsutils
      script: |
        echo "Testing DNS resolution to services..."
        echo "Testing connectivity to Redis..."
        ping -c 2 redis || echo "Could not ping redis service"
        echo "Testing connectivity to MySQL..."
        ping -c 2 mysql || echo "Could not ping mysql service"
        echo "Testing DNS lookup for Redis..."
        nslookup redis || echo "Could not resolve redis"
        echo "Testing DNS lookup for MySQL..."
        nslookup mysql || echo "Could not resolve mysql"
        echo "DNS resolution test completed"

    - name: build
      image: golang:1.21
      script: |
        echo "Building Go application..."
        go version
        echo "Build step completed"

    - name: test
      # This step will use the default image (ubuntu:latest)
      command: ["echo", "Running tests..."]

    - name: package-test
      image: alpine:latest
      packages:
        - curl
        - git
      script: |
        echo "Testing package installation on Alpine..."
        curl --version
        git --version
        echo "Package installation test completed"

    - name: cleanup
      image: alpine:latest
      environment:
        ENVIRONMENT_VARIABLE: "This is an environment variable"
      script: |
        echo "Cleaning up temporary files..."
        echo "Cleanup completed"
        echo $ENVIRONMENT_VARIABLE

pipeline:
  default:
    - setup
    - test-dns
    - package-test
    - build
    - test
    - cleanup
